# Numpy

# 1 Creating  numpy arrays


## 1.1 Using np.array()

In [14]:
import numpy as np
a = np.array([0, 1, 2, 3, 4, 5])
print(type(a))

<class 'numpy.ndarray'>


In [15]:
#Multidimensonal array
arr_0d = np.array(42)
arr_1d=np.array([1,2,3])
arr_2d=np.array([[1,2,3,4],[5,6,7,8]])
arr_3d=np.array([[[1, 2, 3], [4, 5, 6]], [[1, 2, 3], [4, 5, 6]]])

#Checking the array dimension
print(arr_0d.ndim)
print(arr_1d.ndim)
print(arr_2d.ndim)
print(arr_3d.ndim)

0
1
2
3


In [16]:
#Checing the array shape
arr_2d=np.array([[1,2,3,4],[5,6,7,8]])
arr_2d.shape

(2, 4)

## 1.2 Using np.arange()

In [17]:
a = np.arange(5) # 0.... n-1
a

array([0, 1, 2, 3, 4])

In [18]:
b = np.arange(2, 30, 4) #start, end (exclusive), step

b

array([ 2,  6, 10, 14, 18, 22, 26])

# 2 Speed compared to list

In [20]:
L = range(10000)
%timeit [i**3 for i in L]

2.96 ms ± 237 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [21]:
a = np.arange(10000)
%timeit a**3

15.9 µs ± 600 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# 3  Numpy array with diffrent data types

In [22]:
d= np.array([1+2j, 2+4j])   #Complex datatype

print(d.dtype)

complex128


In [23]:
b = np.array([True, False, True, False])  #Boolean datatype

print(b.dtype)

bool


In [24]:
s = np.array(['Ram', 'Robert', 'Rahim'])

s.dtype

dtype('<U6')

# 4 Indexing and Slicing


In [25]:
#Indexing
arr_1d=np.array([1,2,3])
arr_1d[1]

2

In [26]:
#Multi Dimensional Indexing
ingarr_2d=np.array([[1,2,3,4],[5,6,7,8]])
print(arr_2d[0])
print(arr_2d[0][1])

[1 2 3 4]
2


In [27]:
# Slicing
arr_1d=np.array([1,2,3,4])
arr_1d[0:2]

array([1, 2])

In [28]:
#Multi Dimensional Slicing
arr_2d=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
arr_2d[0:2,0:2]

array([[1, 2],
       [5, 6]])

# 5 Element-wise opreation in numpy

## 5.1 Arithmetic Operations With Scalars

In [29]:
arr_1d=np.array([1,2,3,4])
print(arr_1d+4)
print(arr_1d**3)

[5 6 7 8]
[ 1  8 27 64]


## 5.2 Matrix Multiplication

In [30]:
a=np.array([[1,2,3],[4,5,6]])
b=np.array([[7,8,9],[10,11,12]])
print(a*b)

[[ 7 16 27]
 [40 55 72]]


## 5.3 Elementwise comparision

In [31]:
a = np.array([1, 2, 3])
b = np.array([9, 6, 3])
a == b

array([False, False,  True])

## 5.4 Element-wise Logical Operations

In [32]:
a = np.array([True,True,False,False])
b = np.array([True, False, True, False])

np.logical_and(a, b)

array([ True, False, False, False])

In [33]:
#For numeric numpy arrays
a= np.array([1, 5, -2, 0])
b = np.array([1, 0, 1, 0])

np.logical_and(a, b)

array([ True, False,  True, False])

## 5.5 Element-wise Transcendental operations

In [34]:
a = np.array([1, 2, 3])
print(np.cos(a))
print(np.log10(a))
print(np.exp(a))

[ 0.54030231 -0.41614684 -0.9899925 ]
[0.         0.30103    0.47712125]
[ 2.71828183  7.3890561  20.08553692]
